name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
            archive-cmd: tar czf
            suffix: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tar.gz
            archive-cmd: tar czf
            suffix: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: tar.gz
            archive-cmd: tar czf
            suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
            archive-cmd: 7z a
            suffix: .exe

    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Install cross-compilation tools
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
      
      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Create archive
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "target/${{ matrix.target }}/release/tree2md${{ matrix.suffix }}" dist/
            cd dist
            7z a "../tree2md-${{ matrix.target }}.${{ matrix.archive }}" tree2md${{ matrix.suffix }}
          else
            cp "target/${{ matrix.target }}/release/tree2md${{ matrix.suffix }}" dist/
            cd dist
            tar czf "../tree2md-${{ matrix.target }}.${{ matrix.archive }}" tree2md${{ matrix.suffix }}
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree2md-${{ matrix.target }}
          path: tree2md-${{ matrix.target }}.${{ matrix.archive }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: always() && contains(needs.*.result, 'success')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/tree2md-*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-crate:
    name: Publish to crates.io
    needs: release
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        continue-on-error: true